public enum ITEM_TYPE
{
	JEWELRY_RING,
	JEWELRY_NECKLACE,
	JEWELRY_BRACELET,
	ARTIFACT_AMULET,
	ARTIFACT_TALISMAN,
	ARTIFACT_SEAL,
	ARMOR_HELMET,
	ARMOR_UPPER_BODY,
	ARMOR_LOWER_BODY,
	ARMOR_BOOTS,
	ARMOR_GLOVES,
	ARMOR_BRACERS,
	ARMOR_ROBE,
	WEAPON_1H,
	WEAPON_2H
}